name: Geary Erua
  uses: actions/upload-artifact@v1.0.0
  with:
  blank.yml
    name: 
    TestHTML
    path: 

<!DOCTYPE html>

<html>

<body>

<center>

<h2> Classic HTML Design </h2>

<img src = "https://images.pexels.com/photos/270348/pexels-photo-270348.jpeg?cs=srgb&dl=abstract-business-code-coder-270348.jpg&fm=jpg" 
height = "200px" width = "400px" />

<p> This is a very simple HTML design plan. </p>

</center>

</body>

</html>
